name: organicandthecity
favicon: null
layout_spectrum: 0.50334
typography_spectrum: 0.84109
title: The Organic Choice in your City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16110e'
    - '#f2dee0'
    - '#ccb7a2'
    - '#3f3128'
    - '#776758'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.6505711427889764
purpose: []
