name: Organic And The City
favicon: null
layout_spectrum: 0.50334
typography_spectrum: 0.84109
title: The Organic Choice in your City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191a15'
    - '#d7d7d7'
    - '#566f97'
    - '#a28f6f'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.6505711427889764
purpose: []
