name: Organic And The City
favicon: null
layout_spectrum: 0.76044
typography_spectrum: 0.86394
title: Organic And The City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#b8b8b8'
    - '#767676'
    - '#535353'
    - '#ececec'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
