name: Organic And The City
favicon: null
layout_spectrum: 0.7571
typography_spectrum: 0.88898
title: Organic And The City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3c3d'
    - '#14100d'
    - '#cac3ed'
    - '#807966'
    - '#ffae7a'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
