name: Organic And The City
favicon: null
layout_spectrum: 0.75209
typography_spectrum: 0.84109
title: Organic And The City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fcd202'
    - '#567800'
    - '#fa487e'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.6505711427889764
purpose: []
