name: organicandthecity
favicon: null
layout_spectrum: 0.6143301872070879
typography_spectrum: 0.2901743957772851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7742452297825366
  lightness: 0.4639818971045315
  saturation: 0.6641998528502882
  rhythmicContrast: 0.6505711427889764
purpose: []
