name: Organic And The City
favicon: null
layout_spectrum: 0.75209
typography_spectrum: 0.51002
title: Organic And The City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fcd202'
    - '#567800'
    - '#fa487e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
