name: Organic And The City
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84109
title: Organic And The City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e10'
    - '#656b69'
    - '#fffffd'
    - '#918f83'
    - '#b8b29b'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.6505711427889764
purpose: []
